---
# Copy GitHub Repo
- hosts: all
  gather_facts: false

  tasks:
  - name: Install GitHub
    apt:
      name: git
      state: latest
  
  - name: Create directory
    file:
      path: /home/service/repo
      state: directory

  - name: Clone Repo
    git:
      repo: https://github.com/MariuszKn/Ansible_projects.git
      dest: /home/mkociuba/repo
      clone: yes
