---
# Update Windows
- hosts: all
  gather_facts: false
  
  tasks:
  - name: Install all security, critical, and rollup updates without a scheduled task
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
        
  - name: Reboot if wants
    win_reboot:
    when: update_result.reboot_required
